#!/bin/sh

set -euxo pipefail

fbcp &
until ping -c 1 oba_proxy ; do :; done

echo "loading WPE with url: $WPE_URL"

while true; do
  for url in $WPE_URL https://duckduckgo.com/; do
    bash -c 'WPELauncher $WPE_URL > /dev/null' &
    pid=$!
    sleep 10
    kill $pid || true
  done
done

